---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Pages
- type: document
  path: content/homepage.md
  label: Home
- type: document
  path: content/aboutpage.md
  label: About
- type: heading
  label: Work
- type: directory
  path: content/blog
  label: Blog Posts
  create: documents
  match: "**/*"
  templates:
  - blog-post
- type: directory
  path: content/work/projects
  label: Projects
  create: documents
  match: "**/*"
  templates:
  - project
- type: directory
  path: content/speaking
  label: Speaking
  create: documents
  match: "**/*"
  templates:
  - speaking-engagement
- type: heading
  label: Data
- type: document
  path: content/data/contact.yml
  label: Contact List
- type: document
  path: content/data/metadata.yml
  label: Metadata
upload_dir: ''
public_path: https://res.cloudinary.com/zacharybrooks-dev/image/upload
front_matter_path: ''
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_output_directory: dist
  install_dependencies_command: yarn install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: yarn run generate
