---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: document
  path: content/homepage.md
  label: Home
- type: document
  path: content/aboutpage.md
  label: About
- type: directory
  path: content/blog
  label: Blog Posts
  create: documents
  match: "**/*"
- type: directory
  path: content/projects
  label: Projects
  create: documents
  match: "**/*"
- type: document
  path: content/contactpage.md
  label: Contact
- type: document
  path: content/data/contact.yml
  label: Contact List
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
